/* SPDX-FileCopyrightText: 2023 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#include "gpu_shader_create_info.hh"

/* EEVEE_shaders_probe_filter_glossy_sh_get */
GPU_SHADER_NAMED_INTERFACE_INFO(eevee_legacy_lightprobe_vert_geom_iface, vert_iface)
SMOOTH(VEC4, vPos)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_NAMED_INTERFACE_INFO(eevee_legacy_lightprobe_vert_geom_flat_iface, vert_iface_flat)
FLAT(INT, face)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_NAMED_INTERFACE_INFO(eevee_legacy_lightprobe_geom_frag_iface, geom_iface)
SMOOTH(VEC3, worldPosition)
SMOOTH(VEC3, viewPosition)
SMOOTH(VEC3, worldNormal)
SMOOTH(VEC3, viewNormal)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_NAMED_INTERFACE_INFO(eevee_legacy_lightprobe_geom_frag_flat_iface, geom_iface_flat)
FLAT(INT, fFace)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_vert)
VERTEX_IN(0, VEC3, pos)
VERTEX_SOURCE("lightprobe_vert.glsl")
VERTEX_OUT(eevee_legacy_lightprobe_vert_geom_iface)
VERTEX_OUT(eevee_legacy_lightprobe_vert_geom_flat_iface)
BUILTINS(BuiltinBits::INSTANCE_ID)
GPU_SHADER_CREATE_END()

#ifdef WITH_METAL_BACKEND
GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_vert_no_geom)
BUILTINS(BuiltinBits::LAYER)
VERTEX_IN(0, VEC3, pos)
PUSH_CONSTANT(INT, Layer)
VERTEX_SOURCE("lightprobe_vert_no_geom.glsl")
VERTEX_OUT(eevee_legacy_lightprobe_geom_frag_iface)
VERTEX_OUT(eevee_legacy_lightprobe_geom_frag_flat_iface)
BUILTINS(BuiltinBits::INSTANCE_ID)
GPU_SHADER_CREATE_END()
#endif

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_geom)
GEOMETRY_SOURCE("lightprobe_geom.glsl")
GEOMETRY_OUT(eevee_legacy_lightprobe_geom_frag_iface)
GEOMETRY_OUT(eevee_legacy_lightprobe_geom_frag_flat_iface)
PUSH_CONSTANT(INT, Layer)
GEOMETRY_LAYOUT(PrimitiveIn::TRIANGLES, PrimitiveOut::TRIANGLE_STRIP, 3)
GPU_SHADER_CREATE_END()

#ifdef WITH_METAL_BACKEND
GPU_SHADER_CREATE_INFO(eevee_legacy_probe_filter_glossy_no_geom)
ADDITIONAL_INFO(eevee_legacy_lightprobe_vert_no_geom)
FRAGMENT_SOURCE("lightprobe_filter_glossy_frag.glsl")
SAMPLER(0, FLOAT_CUBE, probeHdr)
PUSH_CONSTANT(FLOAT, probe_roughness)
PUSH_CONSTANT(FLOAT, texelSize)
PUSH_CONSTANT(FLOAT, lodFactor)
PUSH_CONSTANT(FLOAT, lodMax)
PUSH_CONSTANT(FLOAT, paddingSize)
PUSH_CONSTANT(FLOAT, intensityFac)
PUSH_CONSTANT(FLOAT, fireflyFactor)
PUSH_CONSTANT(FLOAT, sampleCount)
FRAGMENT_OUT(0, VEC4, FragColor)
METAL_BACKEND_ONLY()
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()
#endif

GPU_SHADER_CREATE_INFO(eevee_legacy_probe_filter_glossy)
ADDITIONAL_INFO(eevee_legacy_lightprobe_vert)
ADDITIONAL_INFO(eevee_legacy_lightprobe_geom)
FRAGMENT_SOURCE("lightprobe_filter_glossy_frag.glsl")
SAMPLER(0, FLOAT_CUBE, probeHdr)
PUSH_CONSTANT(FLOAT, probe_roughness)
PUSH_CONSTANT(FLOAT, texelSize)
PUSH_CONSTANT(FLOAT, lodFactor)
PUSH_CONSTANT(FLOAT, lodMax)
PUSH_CONSTANT(FLOAT, paddingSize)
PUSH_CONSTANT(FLOAT, intensityFac)
PUSH_CONSTANT(FLOAT, fireflyFactor)
PUSH_CONSTANT(FLOAT, sampleCount)
FRAGMENT_OUT(0, VEC4, FragColor)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_effect_downsample_cube_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_downsample_cube)
ADDITIONAL_INFO(eevee_legacy_lightprobe_vert)
ADDITIONAL_INFO(eevee_legacy_lightprobe_geom)
FRAGMENT_SOURCE("effect_downsample_cube_frag.glsl")
SAMPLER(0, FLOAT_CUBE, source)
PUSH_CONSTANT(FLOAT, texelSize)
FRAGMENT_OUT(0, VEC4, FragColor)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

#ifdef WITH_METAL_BACKEND
GPU_SHADER_CREATE_INFO(eevee_legacy_effect_downsample_cube_no_geom)
ADDITIONAL_INFO(eevee_legacy_lightprobe_vert_no_geom)
FRAGMENT_SOURCE("effect_downsample_cube_frag.glsl")
SAMPLER(0, FLOAT_CUBE, source)
PUSH_CONSTANT(FLOAT, texelSize)
FRAGMENT_OUT(0, VEC4, FragColor)
BUILTINS(BuiltinBits::LAYER)
METAL_BACKEND_ONLY()
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()
#endif

/* EEVEE_shaders_probe_filter_diffuse_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_probe_filter_diffuse)
ADDITIONAL_INFO(eevee_legacy_irradiance_lib)
ADDITIONAL_INFO(draw_fullscreen)
FRAGMENT_SOURCE("lightprobe_filter_diffuse_frag.glsl")
SAMPLER(0, FLOAT_CUBE, probeHdr)
PUSH_CONSTANT(INT, probeSize)
PUSH_CONSTANT(FLOAT, lodFactor)
PUSH_CONSTANT(FLOAT, lodMax)
PUSH_CONSTANT(FLOAT, intensityFac)
PUSH_CONSTANT(FLOAT, sampleCount)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_probe_filter_diffuse_sh_l2)
DEFINE("IRRADIANCE_SH_L2")
ADDITIONAL_INFO(eevee_legacy_probe_filter_diffuse)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_probe_filter_diffuse_hl2)
DEFINE("IRRADIANCE_HL2")
ADDITIONAL_INFO(eevee_legacy_probe_filter_diffuse)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_probe_filter_visibility_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_probe_filter_visibility)
DEFINE("IRRADIANCE_HL2")
ADDITIONAL_INFO(eevee_legacy_irradiance_lib)
ADDITIONAL_INFO(draw_fullscreen)
FRAGMENT_SOURCE("lightprobe_filter_visibility_frag.glsl")
SAMPLER(0, FLOAT_CUBE, probeDepth)
PUSH_CONSTANT(INT, outputSize)
PUSH_CONSTANT(FLOAT, lodFactor)
PUSH_CONSTANT(FLOAT, storedTexelSize)
PUSH_CONSTANT(FLOAT, lodMax)
PUSH_CONSTANT(FLOAT, nearClip)
PUSH_CONSTANT(FLOAT, farClip)
PUSH_CONSTANT(FLOAT, visibilityRange)
PUSH_CONSTANT(FLOAT, visibilityBlur)
PUSH_CONSTANT(FLOAT, sampleCount)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
DO_STATIC_COMPILATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_probe_grid_fill_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_probe_grid_fill)
ADDITIONAL_INFO(draw_fullscreen)
FRAGMENT_SOURCE("lightprobe_grid_fill_frag.glsl")
SAMPLER(0, FLOAT_2D_ARRAY, irradianceGrid)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_probe_grid_fill_sh_l2)
DEFINE("IRRADIANCE_SH_L2")
ADDITIONAL_INFO(eevee_legacy_probe_grid_fill)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_probe_grid_fill_hl2)
DEFINE("IRRADIANCE_HL2")
ADDITIONAL_INFO(eevee_legacy_probe_grid_fill)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_probe_planar_display_sh_get */
GPU_SHADER_INTERFACE_INFO(legacy_probe_planar_iface)
SMOOTH(VEC3, worldPosition)
FLAT(INT, probeIdx)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_probe_planar_display)
SAMPLER(0, FLOAT_2D_ARRAY, probePlanars)
VERTEX_IN(0, VEC3, pos)
VERTEX_IN(1, INT, probe_id)
VERTEX_IN(2, MAT4, probe_mat)
VERTEX_OUT(legacy_probe_planar_iface)
VERTEX_SOURCE("lightprobe_planar_display_vert.glsl")
FRAGMENT_SOURCE("lightprobe_planar_display_frag.glsl")
ADDITIONAL_INFO(draw_view)
FRAGMENT_OUT(0, VEC4, FragColor)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_studiolight_probe_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_studiolight_probe)
ADDITIONAL_INFO(draw_resource_id_varying)
ADDITIONAL_INFO(eevee_legacy_lightprobe_lib)
ADDITIONAL_INFO(eevee_legacy_surface_lib_lookdev)
VERTEX_IN(0, VEC2, pos)
SAMPLER(0, FLOAT_2D, studioLight)
PUSH_CONSTANT(FLOAT, backgroundAlpha)
PUSH_CONSTANT(MAT3, StudioLightMatrix)
PUSH_CONSTANT(FLOAT, studioLightIntensity)
PUSH_CONSTANT(FLOAT, studioLightBlur)
FRAGMENT_OUT(0, VEC4, FragColor)
VERTEX_SOURCE("background_vert.glsl")
FRAGMENT_SOURCE("lookdev_world_frag.glsl")
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_studiolight_background_sh_get */
GPU_SHADER_CREATE_INFO(eevee_legacy_studiolight_background)
DEFINE("LOOKDEV_BG")
ADDITIONAL_INFO(eevee_legacy_studiolight_probe)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_probe_planar_downsample_sh_get */

GPU_SHADER_NAMED_INTERFACE_INFO(eevee_legacy_probe_planar_downsample_vert_geom_iface, lightprobe_vert_iface)
SMOOTH(VEC2, vPos)
GPU_SHADER_INTERFACE_END()
GPU_SHADER_NAMED_INTERFACE_INFO(eevee_legacy_probe_planar_downsample_vert_geom_flat_iface, lightprobe_vert_iface_flat)
FLAT(INT, instance)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_NAMED_INTERFACE_INFO(eevee_legacy_probe_planar_downsample_geom_frag_iface, lightprobe_geom_iface)
FLAT(FLOAT, layer)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_planar_downsample_common)
VERTEX_SOURCE("lightprobe_planar_downsample_vert.glsl")
FRAGMENT_SOURCE("lightprobe_planar_downsample_frag.glsl")
VERTEX_OUT(eevee_legacy_probe_planar_downsample_vert_geom_iface)
VERTEX_OUT(eevee_legacy_probe_planar_downsample_vert_geom_flat_iface)
SAMPLER(0, FLOAT_2D_ARRAY, source)
PUSH_CONSTANT(FLOAT, fireflyFactor)
FRAGMENT_OUT(0, VEC4, FragColor)
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_planar_downsample)
ADDITIONAL_INFO(eevee_legacy_lightprobe_planar_downsample_common)
GEOMETRY_SOURCE("lightprobe_planar_downsample_geom.glsl")
GEOMETRY_OUT(eevee_legacy_probe_planar_downsample_geom_frag_iface)
GEOMETRY_LAYOUT(PrimitiveIn::TRIANGLES, PrimitiveOut::TRIANGLE_STRIP, 3)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

#ifdef WITH_METAL_BACKEND
GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_planar_downsample_no_geom)
ADDITIONAL_INFO(eevee_legacy_lightprobe_planar_downsample_common)
BUILTINS(BuiltinBits::LAYER)
VERTEX_OUT(eevee_legacy_probe_planar_downsample_geom_frag_iface)
METAL_BACKEND_ONLY()
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()
#endif

/* EEVEE_shaders_probe_cube_display_sh_get */
GPU_SHADER_INTERFACE_INFO(eevee_legacy_lightprobe_cube_display_iface)
FLAT(INT, pid)
SMOOTH(VEC2, quadCoord)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_cube_display)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_lightprobe_lib)
VERTEX_SOURCE("lightprobe_cube_display_vert.glsl")
FRAGMENT_SOURCE("lightprobe_cube_display_frag.glsl")
VERTEX_OUT(eevee_legacy_lightprobe_cube_display_iface)
PUSH_CONSTANT(FLOAT, sphere_size)
PUSH_CONSTANT(VEC3, screen_vecs)
FRAGMENT_OUT(0, VEC4, FragColor)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

/* EEVEE_shaders_probe_grid_display_sh_get */
GPU_SHADER_INTERFACE_INFO(eevee_legacy_lightprobe_grid_display_iface)
FLAT(INT, cellOffset)
SMOOTH(VEC2, quadCoord)
GPU_SHADER_INTERFACE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_grid_display_common)
ADDITIONAL_INFO(eevee_legacy_common_lib)
ADDITIONAL_INFO(draw_view)
ADDITIONAL_INFO(eevee_legacy_irradiance_lib)
VERTEX_SOURCE("lightprobe_grid_display_vert.glsl")
FRAGMENT_SOURCE("lightprobe_grid_display_frag.glsl")
VERTEX_OUT(eevee_legacy_lightprobe_grid_display_iface)
PUSH_CONSTANT(FLOAT, sphere_size)
PUSH_CONSTANT(INT, offset)
PUSH_CONSTANT(IVEC3, grid_resolution)
PUSH_CONSTANT(VEC3, corner)
PUSH_CONSTANT(VEC3, increment_x)
PUSH_CONSTANT(VEC3, increment_y)
PUSH_CONSTANT(VEC3, increment_z)
PUSH_CONSTANT(VEC3, screen_vecs)
FRAGMENT_OUT(0, VEC4, FragColor)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_grid_display_common_sh_l2)
DEFINE("IRRADIANCE_SH_L2")
ADDITIONAL_INFO(eevee_legacy_lightprobe_grid_display_common)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()

GPU_SHADER_CREATE_INFO(eevee_legacy_lightprobe_grid_display_common_hl2)
DEFINE("IRRADIANCE_HL2")
ADDITIONAL_INFO(eevee_legacy_lightprobe_grid_display_common)
DO_STATIC_COMPILATION()
AUTO_RESOURCE_LOCATION()
GPU_SHADER_CREATE_END()